config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index";

  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  # validates :name, precence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    # @groups = Group.all
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index 
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path
    else
      redirect_to group_messages_path
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to group_messages_path
  end

private
  require 'open3'
  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_helper.rb
module GoogleHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/_group_index.html.haml
.main
  - current_user.groups.each do |group|
    .main__groups
      .main__groups__name
        = link_to group_messages_path(group) do
          = group.name
      .main__groups__date
        作成日:
        = group.created_at.strftime("%Y年%m月%d日 %H時%M分")

app/views/groups/_header.html.haml
.header
  .header__box
    .header__box__title
      minute App
    %ul.header__box__config
      %li.header__box__config__user
        Name:
        =current_user.name
      %li.header__box__config__icon--cog
        =link_to "#" do
          =icon("fas","user-cog")
      %li.header__box__config__icon--edit
        =link_to new_group_path do
          =icon("fas","edit")
      = link_to destroy_user_session_path, class: "header__box__config__btn" do
        Edit

app/views/groups/index.html.haml
.wrapper
  = render 'header'
  = render 'group_index'

app/views/groups/new.html.haml
.new-chat-group-title
  新規議事録の作成

= form_for @group do |f|
  = f.text_field :name, class: "chat-group-form__input", placeholder: "議事録名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_参加者を選択してください"} 参加者を選択してください
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "作成", class: "chat-group-form__action-btn"

= link_to root_path, class: "chat-group-form__return-btn" do
  戻る

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title MinutesApp
    = csrf_meta_tags
    = javascript_pack_tag 'application'
    = stylesheet_link_tag    'application', media: 'all'
    = csp_meta_tag
    -# = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_header.html.haml
.message-header
  .message-header__box
    .message-header__box__title
      = @group.name
    .message-header__box__user
      Member:
      - @group.group_users.each do |group_user|
        = group_user.user.name
    %ul.message-header__box__config
      %li.message-header__box__config__icon--cog
        =link_to "#" do
          =icon("fas","user-cog")
      %li.message-header__box__config__icon--edit
        =link_to new_group_path do
          =icon("fas","edit")
      = link_to root_path, class: "message-header__box__config__btn" do
        一覧に戻る

app/views/messages/_main.html.haml
.messages
  = render @messages

.form
  = form_for [@group, @message] do |f|
    .form__box
      = f.text_field :text, class: 'form__box__text', placeholder: 'type a message'
      = f.label :image, class: 'form__box__image' do
        = icon("fas", "image")
        = f.file_field :image, class: 'form__box__hidden'
    = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
.message
  %ul.message__box
    %li.message__box__name
      = message.user.name
    %li.message__box__message
      = message.text
    = image_tag message.image.url, class: 'message__image' if message.image.present?
    .message__box__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .message__box__delete
      = link_to '削除', "/groups/#{@group.id}/messages/#{message.id}", method: :delete

app/views/messages/index.html.haml
.wapper
  =render "header"
  =render "main" 

app/views/messages/new.html.haml
.wrapper
  =render "header"
  =render "new__main"